library(tm)
library(wordcloud)

stopwords1 <- as.list(c("thielcollege", "thiel college", "college", "thiel", "got", "like", "getting", "just", "...", "'re", '"?@collegefession: ', "will", "greenville, ", "shave", "pubes"))
twitter <- Corpus(DirSource("C:/Users/110427052/Desktop/Documents/Twitter/"))
inspect(twitter)
twitterclean<-tm_map(twitter, stripWhitespace)
twitterclean <- tm_map(twitterclean, tolower)
twitterclean <- tm_map(twitterclean, removeWords, stopwords('english'))
twitterclean <- tm_map(twitterclean, removeWords, stopwords1)
twitterclean<-tm_map(twitterclean, stripWhitespace)
twitterclean <- tm_map(twitterclean, stemDocument)
twitterclean <- tm_map(twitterclean, PlainTextDocument)
wordcloud(twitterclean, max.words = 100, random.order = FALSE, scale=c(2, 0.25), colors = brewer.pal(8, "Dark2"), use.r.layout = FALSE)
wordcloud(twitterclean, max.words = 25, random.order = FALSE, scale=c(2, 0.25), colors = brewer.pal(8, "Dark2"), use.r.layout = FALSE)
